name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Upload to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          # Install necessary dependencies
          sudo apt-get update
          sudo apt-get install -y openssh-client
          
          # Upload gradle-wrapper.jar to EC2
          scp -o StrictHostKeyChecking=no -i $EC2_KEY gradle-wrapper.jar $EC2_USER@$EC2_HOST:/home/ec2-user/app/
