name: Build and Deploy to EC2

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 워크플로우가 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload JAR file
        uses: actions/upload-artifact@v2
        with:
          name: jar-file
          path: target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: jar-file
          path: .

      - name: Copy JAR file via SCP
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          scp -o StrictHostKeyChecking=no -i $KEY target/*.jar $USERNAME@$HOST:/home/ubuntu/app.jar

      - name: SSH and restart application
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USER }}
          KEY: ${{ secrets.EC2_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $KEY $USERNAME@$HOST << 'EOF'
          sudo systemctl stop myapp
          sudo systemctl start myapp
          EOF